"""Pydantic response/request models shared across routers."""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, field_validator


class Quote(BaseModel):
    symbol: str
    name: Optional[str] = None
    price: float
    change: float
    change_pct: float
    currency: str = "USD"
    market_cap: Optional[float] = None
    volume: Optional[float] = None
    source: str = "live"  # "live" | "mock"


class Indicators(BaseModel):
    rsi: Optional[float] = None
    rsi_prev: Optional[float] = None      # RSI one bar ago (cross detection)
    rsi_min_10d: Optional[float] = None   # lowest RSI in the last 10 bars
    ret_5d_pct: Optional[float] = None    # 5-bar price change % (ignition)
    ret_20d_pct: Optional[float] = None   # 20-bar price change % (momentum)
    macd: Optional[float] = None
    macd_signal: Optional[float] = None
    macd_hist: Optional[float] = None
    sma20: Optional[float] = None
    sma50: Optional[float] = None
    sma200: Optional[float] = None
    ema20: Optional[float] = None
    atr: Optional[float] = None
    bb_upper: Optional[float] = None
    bb_lower: Optional[float] = None
    high_52w: Optional[float] = None
    low_52w: Optional[float] = None
    pct_from_52w_high: Optional[float] = None
    avg_volume_20: Optional[float] = None
    volume_ratio: Optional[float] = None  # today's volume / 20d avg
    trend: Optional[str] = None  # "uptrend" | "downtrend" | "sideways"


class AnalystView(BaseModel):
    recommendation: Optional[str] = None
    mean_target: Optional[float] = None
    high_target: Optional[float] = None
    low_target: Optional[float] = None
    num_analysts: Optional[int] = None
    upside_pct: Optional[float] = None


class NewsItem(BaseModel):
    title: str
    publisher: Optional[str] = None
    link: Optional[str] = None
    published: Optional[str] = None


class Signal(BaseModel):
    label: str
    kind: str  # "bullish" | "bearish" | "neutral"
    detail: str


class StockReport(BaseModel):
    symbol: str
    theme: Optional[str] = None
    quote: Quote
    indicators: Indicators
    analyst: AnalystView
    news: list[NewsItem] = []
    signals: list[Signal] = []
    # Position economics (present only for held names)
    shares: Optional[float] = None
    cost_basis: Optional[float] = None
    market_value: Optional[float] = None
    unrealized_pl: Optional[float] = None
    unrealized_pl_pct: Optional[float] = None
    # Recent close series (~30 pts) for an inline sparkline on cards.
    spark: list[float] = []
    # Binary-event awareness
    earnings_date: Optional[str] = None
    days_to_earnings: Optional[int] = None


class RunnerCandidate(BaseModel):
    """A low-float / high-velocity name — the MGRT-type explosive setup."""
    symbol: str
    name: Optional[str] = None
    theme: Optional[str] = None
    price: float
    change_pct: float
    runner_score: float  # 0-100 explosive-setup readiness
    stage: str  # "coiled" | "igniting" | "extended" | "cooling"
    # structural DNA
    float_shares: Optional[float] = None
    market_cap: Optional[float] = None
    short_pct_float: Optional[float] = None
    float_pct: Optional[float] = None
    recent_ipo: bool = False
    # velocity
    volume_ratio: Optional[float] = None
    ret_5d_pct: Optional[float] = None
    ret_20d_pct: Optional[float] = None
    rsi: Optional[float] = None
    reasons: list[str] = []  # why it scored — the teachable characteristics
    caution: Optional[str] = None  # the honest risk note


class BreakoutCandidate(BaseModel):
    symbol: str
    theme: Optional[str] = None
    score: float  # 0-100 composite breakout readiness
    price: float
    quote: Quote
    indicators: Indicators
    signals: list[Signal] = []
    thesis: Optional[str] = None       # joined fallback for older clients
    thesis_points: list[str] = []      # bullet form — preferred by the UI


class AdvisorNote(BaseModel):
    """Advisor output is bullet-first: short scannable points, never prose walls."""
    symbol: str
    persona: str
    engine: str  # "claude" | "fallback"
    generated_at: str
    summary: str                # 1-2 sentence overall take
    posture: Optional[str] = None  # "act" | "watch" — patience is a position
    call: Optional[str] = None  # one-word standing stance: BUY/ADD/HOLD/TRIM/SELL/AVOID/WATCH
    insights: list[str] = []    # technical / portfolio-health observations
    mix: list[str] = []         # allocation health — "is the mix still right?"
    positions: list[str] = []   # per-name color on notable holdings (leaders/laggards/movers)
    actions: list[str] = []     # concrete recommendations (ticker + level each)
    risks: list[str] = []       # each risk paired with its confirming signal
    scout: list[str] = []       # not-owned growth names to accumulate toward
    # THE PLAN, generated by the brief itself. There is no separate transition
    # feature: a second surface issuing orders is what produced contradictory
    # advice ("sell what you were told to buy today").
    sequence: list["AdvisorStep"] = []
    raw: Optional[str] = None


class AdvisorStep(BaseModel):
    """One staged move in the brief's plan."""
    n: int
    when: str        # "immediately" or a concrete trigger price
    do: str          # the order in plain words
    why: str = ""


class PortfolioSummary(BaseModel):
    total_market_value: float   # positions + cash (matches the broker account value)
    total_cost: float
    total_unrealized_pl: float
    total_unrealized_pl_pct: float
    day_change: float
    day_change_pct: float
    positions: int
    cash: float = 0.0           # uninvested buying power, included in total above
    source: str
    by_theme: dict[str, float] = {}
    realized_pl: float = 0.0    # booked gains/losses from closed & trimmed positions
    total_return: float = 0.0   # realized + unrealized — the real "how am I doing"
    total_return_pct: float = 0.0


class PinCreate(BaseModel):
    """Pin an advisor recommendation to the persistent action list."""
    symbol: Optional[str] = None
    source: str = "advisor"  # "brief" | "advisor" | "ask" | "signal"
    text: str = Field(min_length=1, max_length=1000)
    points: list[str] = []


class PinUpdate(BaseModel):
    status: str  # "open" | "done"

    @field_validator("status")
    @classmethod
    def _valid_status(cls, v: str) -> str:
        v = (v or "").strip().lower()
        if v not in {"open", "done"}:
            raise ValueError("status must be open or done")
        return v


class JournalCreate(BaseModel):
    """A manually recorded move for the action journal."""
    symbol: Optional[str] = None
    action: str  # "buy" | "sell" | "note"
    date: Optional[str] = None       # YYYY-MM-DD; default today
    shares: Optional[float] = Field(default=None, ge=0)
    price: Optional[float] = Field(default=None, ge=0)
    note: str = ""
    cost_basis: Optional[float] = Field(default=None, ge=0)
    realized_pl: Optional[float] = None  # booked $ gain/loss on a sell

    @field_validator("action")
    @classmethod
    def _valid_action(cls, v: str) -> str:
        v = (v or "").strip().lower()
        if v not in {"buy", "sell", "note"}:
            raise ValueError("action must be buy, sell or note")
        return v


class JournalUpdate(BaseModel):
    symbol: Optional[str] = None
    action: Optional[str] = None
    date: Optional[str] = None
    shares: Optional[float] = Field(default=None, ge=0)
    price: Optional[float] = Field(default=None, ge=0)
    note: Optional[str] = None
    cost_basis: Optional[float] = Field(default=None, ge=0)
    realized_pl: Optional[float] = None


class AskRequest(BaseModel):
    """A follow-up question about a prior advisor note."""
    kind: str  # "portfolio" | "stock" | "breakout" | "strategy"
    symbol: Optional[str] = None
    question: str = Field(min_length=1, max_length=2000)
    deep: bool = False  # allow web research (slower, live news/sentiment)

    @field_validator("kind")
    @classmethod
    def _valid_kind(cls, v: str) -> str:
        v = (v or "").strip().lower()
        if v not in {"portfolio", "stock", "breakout", "strategy"}:
            raise ValueError("kind must be portfolio, stock, breakout or strategy")
        return v


class DeviceRegister(BaseModel):
    """A native-app device registering for push notifications."""
    token: str = Field(min_length=1)
    platform: Optional[str] = None  # ios | android


class WatchpointCreate(BaseModel):
    """A standing price/RSI tripwire that fires a slap alert when met."""
    symbol: str = Field(min_length=1)
    kind: str  # price_below | price_above | rsi_below | rsi_above
    level: float = Field(gt=0)
    note: str = Field(default="", max_length=300)
    side: Optional[str] = None  # buy | sell (slap styling); inferred if omitted
    confirm: str = "touch"  # "close" = only fire near/after the session close

    @field_validator("confirm")
    @classmethod
    def _valid_confirm(cls, v: str) -> str:
        v = (v or "touch").strip().lower()
        if v not in {"touch", "close"}:
            raise ValueError("confirm must be touch or close")
        return v

    @field_validator("kind")
    @classmethod
    def _valid_kind(cls, v: str) -> str:
        v = (v or "").strip().lower()
        if v not in {"price_below", "price_above", "rsi_below", "rsi_above"}:
            raise ValueError("kind must be price_below/price_above/rsi_below/rsi_above")
        return v

    @field_validator("symbol")
    @classmethod
    def _upper(cls, v: str) -> str:
        v = (v or "").strip().upper()
        if not v:
            raise ValueError("symbol required")
        return v


class RecommendRequest(BaseModel):
    """Ask the advisor what to do about a notification event."""
    symbol: str = Field(min_length=1)
    event: str = Field(min_length=1, max_length=300)
    kind: str = "alert"  # alert | signal | runner


class StrategyGenRequest(BaseModel):
    """Client goals feeding strategy generation."""
    target_value: Optional[float] = Field(default=None, ge=0)
    horizon: Optional[str] = None            # e.g. "5 years"
    monthly_contribution: Optional[float] = Field(default=None, ge=0)
    risk_appetite: Optional[str] = None      # conservative | balanced | aggressive
    notes: Optional[str] = Field(default=None, max_length=2000)
    deep: bool = False


# ------------------------------------------------------------- intelligence
class PortfolioAlert(BaseModel):
    """A rule-derived attention item for the dashboard alerts panel."""
    symbol: str
    severity: str  # "critical" | "warning" | "opportunity"
    label: str
    detail: str
    id: Optional[str] = None  # stable key (symbol:label) for dismissal


class RiskMetrics(BaseModel):
    beta: Optional[float] = None              # vs SPY, ~6mo daily returns
    volatility_pct: Optional[float] = None    # annualized stdev of daily returns
    sharpe: Optional[float] = None            # annualized, 4% risk-free
    max_drawdown_pct: Optional[float] = None  # worst peak-to-trough, 1y
    best_day_pct: Optional[float] = None
    best_day_date: Optional[str] = None
    worst_day_pct: Optional[float] = None
    worst_day_date: Optional[str] = None
    top_symbol: Optional[str] = None          # largest position
    top_weight_pct: Optional[float] = None
    top5_weight_pct: Optional[float] = None


class PortfolioInsights(BaseModel):
    source: str  # "live" | "mock"
    risk: RiskMetrics
    alerts: list[PortfolioAlert] = []


# ---------------------------------------------------------------- risk desk
class PositionRisk(BaseModel):
    """Per-holding open risk: how much is on the table down to the stop."""
    symbol: str
    price: float
    market_value: float
    weight_pct: float
    stop: Optional[float] = None
    stop_basis: Optional[str] = None       # "2.0x ATR" | "200-day" | None
    stop_distance_pct: Optional[float] = None
    risk_amount: Optional[float] = None    # $ lost if the stop trades
    risk_pct_of_equity: Optional[float] = None
    over_size: bool = False                # breaches MAX_POSITION_PCT


class PositionPlan(BaseModel):
    """Pre-trade sizing for one candidate — the answer to 'how much?'."""
    symbol: str
    price: float
    stop: Optional[float] = None
    stop_basis: Optional[str] = None
    risk_per_share: Optional[float] = None
    dollars: float = 0.0                   # position size to buy
    shares: float = 0.0                    # fractional shares allowed
    pct_of_equity: float = 0.0
    risk_amount: float = 0.0               # $ risked to the stop
    capped_by: Optional[str] = None        # "max position" | "dry powder" | None
    note: str = ""


class RiskDesk(BaseModel):
    """The whole risk picture: limits, open risk, and the exposure overview."""
    equity: float
    invested: float
    cash: float
    status: str                            # PROTECTED | ELEVATED | BREACHED
    # 01 position size
    risk_per_trade_pct: float
    risk_budget_amount: float
    # 02/03 stops + daily limits
    daily_loss_limit_pct: float
    daily_loss_limit_amount: float
    day_pl: float
    day_pl_pct: float
    limit_breached: bool
    # 04 portfolio risk
    portfolio_risk_pct: Optional[float] = None
    portfolio_risk_amount: Optional[float] = None
    exposure_utilization_pct: float = 0.0
    positions: list[PositionRisk] = []
    # 05 overview strip
    max_drawdown_pct: Optional[float] = None
    var95_pct: Optional[float] = None
    var95_amount: Optional[float] = None
    beta: Optional[float] = None
    avg_correlation: Optional[float] = None
    liquidity: Optional[str] = None        # HIGH | MEDIUM | LOW
    # honesty
    history_days: int = 0
    notes: list[str] = []
    metrics: RiskMetrics = RiskMetrics()
    source: str = "live"


class PortfolioNewsItem(BaseModel):
    """A news headline tagged with the symbol(s) it came from."""
    title: str
    symbols: list[str] = []
    publisher: Optional[str] = None
    link: Optional[str] = None
    published: Optional[str] = None


# --------------------------------------------------------------- config I/O
class Holding(BaseModel):
    """A held position. shares/cost_basis drive the P/L math."""
    symbol: str
    shares: float = Field(ge=0)
    cost_basis: float = Field(ge=0)
    theme: Optional[str] = None

    @field_validator("symbol")
    @classmethod
    def _upper_symbol(cls, v: str) -> str:
        v = (v or "").strip().upper()
        if not v:
            raise ValueError("symbol is required")
        return v


class WatchItem(BaseModel):
    """A name you're watching but don't hold."""
    symbol: str
    theme: Optional[str] = None

    @field_validator("symbol")
    @classmethod
    def _upper_symbol(cls, v: str) -> str:
        v = (v or "").strip().upper()
        if not v:
            raise ValueError("symbol is required")
        return v


class PortfolioConfig(BaseModel):
    """The full editable portfolio config persisted to portfolio.json."""
    owner: str = "You"
    advisor_persona: str = "senior financial advisor at Charles Schwab"
    cash: float = 0.0    # uninvested buying power — counts toward total & allocation
    # symbols the client holds as long-term CONVICTIONS: accumulate on weakness,
    # never told to sell at a loss on a technical break (only if thesis breaks)
    core_convictions: list[str] = []
    # When dry powder is low, stop alerting/enriching runners + not-owned buys
    # (nothing to act on there) and only watch names you actually hold. Saves
    # Claude usage when there's no cash to deploy.
    quiet_unowned_low_cash: bool = True
    # Only fire buy/sell SIGNALS for names you actually hold or watch. The
    # discovery universe is market-wide now (~190 tickers), so scanning it for
    # slaps produces alerts on names with no place in the book. Discovery and
    # the advisor's scouting are unaffected — this gates the signal engine only.
    signals_owned_only: bool = True
    # The ONLY standing guidance the advisor gets. This replaced a generated
    # strategy document with allocation targets, guardrails and milestones —
    # that doc accumulated stale claims and ended up contradicting the live
    # brief, so it was removed. One sentence the client controls, nothing
    # derived, nothing to drift out of sync.
    risk_profile: str = (
        "Aggressive risk profile targeting double-digit annual growth, with "
        "little or no additional capital being contributed."
    )
    themes: dict[str, str] = {}
    holdings: list[Holding] = []
    watchlist: list[WatchItem] = []


# ----------------------------------------------------------------- charting
class Candle(BaseModel):
    date: str          # ISO date (YYYY-MM-DD) or "YYYY-MM-DD HH:MM" intraday
    open: float
    high: float
    low: float
    close: float
    volume: float
    sma20: Optional[float] = None
    sma50: Optional[float] = None
    rsi: Optional[float] = None  # RSI(14) over the same bars, for the RSI pane


class PriceHistory(BaseModel):
    symbol: str
    range: str          # "1mo" | "3mo" | "6mo" | "1y"
    source: str         # "live" | "mock"
    candles: list[Candle] = []


class ValuePoint(BaseModel):
    date: str           # ISO date (YYYY-MM-DD)
    value: float        # portfolio market value on that day


class PortfolioHistory(BaseModel):
    range: str          # "1mo" | "3mo" | "6mo" | "1y"
    source: str         # "live" | "mock"
    cost_basis: float   # flat total cost baseline
    points: list[ValuePoint] = []
    # The index over the same window, REBASED to the portfolio's starting value
    # so both lines share one axis and the gap between them is the answer to
    # "am I beating the market or just riding it".
    benchmark: list[ValuePoint] = []
    benchmark_symbol: str = "SPY"
